# [Predict Introverts from Extroverts](https://www.kaggle.com/competitions/playground-series-s5e7/)
---

In [1]:
# !kaggle competitions download -c playground-series-s5e7
# !unzip playground-series-s5e7.zip
# !rm playground-series-s5e7.zip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
df_train = pd.read_csv("train.csv", index_col="id")
df_train.head()

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
id                                                                        
0                0.0         No                      6.0            4.0   
1                1.0         No                      7.0            3.0   
2                6.0        Yes                      1.0            0.0   
3                3.0         No                      7.0            3.0   
4                1.0         No                      4.0            4.0   

   Drained_after_socializing  Friends_circle_size  Post_frequency Personality  
id                                                                             
0                         No                 15.0             5.0   Extrovert  
1                         No                 10.0             8.0   Extrovert  
2                        NaN                  3.0             0.0   Introvert  
3                         No                 11.0             5.0   Extrovert  
4                         No                 13.0             NaN   Extrovert

In [4]:
df_test = pd.read_csv("test.csv", index_col="id")
df_test.head()

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
id                                                                           
18524               3.0         No                      7.0            4.0   
18525               NaN        Yes                      0.0            0.0   
18526               3.0         No                      5.0            6.0   
18527               3.0         No                      4.0            4.0   
18528               9.0        Yes                      1.0            2.0   

      Drained_after_socializing  Friends_circle_size  Post_frequency  
id                                                                    
18524                        No                  6.0             NaN  
18525                       Yes                  5.0             1.0  
18526                        No                 15.0             9.0  
18527                        No                  5.0             6.0  
18528                       Yes                  1.0             1.0

In [5]:
df_train.describe()

Time_spent_Alone  Social_event_attendance  Going_outside  \
count      17334.000000             17344.000000   17058.000000   
mean           3.137764                 5.265106       4.044319   
std            3.003786                 2.753359       2.062580   
min            0.000000                 0.000000       0.000000   
25%            1.000000                 3.000000       3.000000   
50%            2.000000                 5.000000       4.000000   
75%            4.000000                 8.000000       6.000000   
max           11.000000                10.000000       7.000000   

       Friends_circle_size  Post_frequency  
count         17470.000000    17260.000000  
mean              7.996737        4.982097  
std               4.223484        2.879139  
min               0.000000        0.000000  
25%               5.000000        3.000000  
50%               8.000000        5.000000  
75%              12.000000        7.000000  
max              15.000000       10.000000

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18524 entries, 0 to 18523
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           17334 non-null  float64
 1   Stage_fear                 16631 non-null  object 
 2   Social_event_attendance    17344 non-null  float64
 3   Going_outside              17058 non-null  float64
 4   Drained_after_socializing  17375 non-null  object 
 5   Friends_circle_size        17470 non-null  float64
 6   Post_frequency             17260 non-null  float64
 7   Personality                18524 non-null  object 
dtypes: float64(5), object(3)
memory usage: 1.3+ MB


In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6175 entries, 18524 to 24698
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           5750 non-null   float64
 1   Stage_fear                 5577 non-null   object 
 2   Social_event_attendance    5778 non-null   float64
 3   Going_outside              5709 non-null   float64
 4   Drained_after_socializing  5743 non-null   object 
 5   Friends_circle_size        5825 non-null   float64
 6   Post_frequency             5767 non-null   float64
dtypes: float64(5), object(2)
memory usage: 385.9+ KB


## Basic Data Cleaning
---

In [8]:
df_train_clean = df_train.copy(deep=True)
df_test_clean = df_test.copy(deep=True)

### Converting to Numeric

In [9]:
df_train_clean.head()

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
id                                                                        
0                0.0         No                      6.0            4.0   
1                1.0         No                      7.0            3.0   
2                6.0        Yes                      1.0            0.0   
3                3.0         No                      7.0            3.0   
4                1.0         No                      4.0            4.0   

   Drained_after_socializing  Friends_circle_size  Post_frequency Personality  
id                                                                             
0                         No                 15.0             5.0   Extrovert  
1                         No                 10.0             8.0   Extrovert  
2                        NaN                  3.0             0.0   Introvert  
3                         No                 11.0             5.0   Extrovert  
4                         No                 13.0             NaN   Extrovert

In [10]:
df_test_clean.head()

Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
id                                                                           
18524               3.0         No                      7.0            4.0   
18525               NaN        Yes                      0.0            0.0   
18526               3.0         No                      5.0            6.0   
18527               3.0         No                      4.0            4.0   
18528               9.0        Yes                      1.0            2.0   

      Drained_after_socializing  Friends_circle_size  Post_frequency  
id                                                                    
18524                        No                  6.0             NaN  
18525                       Yes                  5.0             1.0  
18526                        No                 15.0             9.0  
18527                        No                  5.0             6.0  
18528                       Yes                  1.0             1.0

In [11]:
df_train_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18524 entries, 0 to 18523
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           17334 non-null  float64
 1   Stage_fear                 16631 non-null  object 
 2   Social_event_attendance    17344 non-null  float64
 3   Going_outside              17058 non-null  float64
 4   Drained_after_socializing  17375 non-null  object 
 5   Friends_circle_size        17470 non-null  float64
 6   Post_frequency             17260 non-null  float64
 7   Personality                18524 non-null  object 
dtypes: float64(5), object(3)
memory usage: 1.3+ MB


In [12]:
df_test_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6175 entries, 18524 to 24698
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Time_spent_Alone           5750 non-null   float64
 1   Stage_fear                 5577 non-null   object 
 2   Social_event_attendance    5778 non-null   float64
 3   Going_outside              5709 non-null   float64
 4   Drained_after_socializing  5743 non-null   object 
 5   Friends_circle_size        5825 non-null   float64
 6   Post_frequency             5767 non-null   float64
dtypes: float64(5), object(2)
memory usage: 385.9+ KB


#### Stage Fear

In [13]:
df_train["Stage_fear"].unique()

array(['No', 'Yes', nan], dtype=object)

In [14]:
df_train_clean["Stage_fear"] = df_train["Stage_fear"].map({"No": 0, "Yes": 1})

df_train_clean["Stage_fear"].unique()

array([ 0.,  1., nan])

In [15]:
df_test_clean["Stage_fear"] = df_test["Stage_fear"].map({"No": 0, "Yes": 1})

df_test_clean["Stage_fear"].unique()

array([ 0.,  1., nan])

#### Drained after socialising

In [16]:
df_train["Drained_after_socializing"].unique()

array(['No', nan, 'Yes'], dtype=object)

In [17]:
df_train_clean["Drained_after_socializing"] = df_train["Drained_after_socializing"].map(
    {"No": 0, "Yes": 1}
)

df_train_clean["Drained_after_socializing"].unique()

array([ 0., nan,  1.])

In [18]:
df_test_clean["Drained_after_socializing"] = df_test["Drained_after_socializing"].map(
    {"No": 0, "Yes": 1}
)

df_test_clean["Drained_after_socializing"].unique()

array([ 0.,  1., nan])

#### Target 'Personality'

In [19]:
df_train["Personality"].unique()

array(['Extrovert', 'Introvert'], dtype=object)

In [20]:
df_train_clean["Personality"] = df_train["Personality"].map(
    {"Introvert": 0, "Extrovert": 1}
)
df_train_clean["Personality"].unique()

array([1, 0])

### Imputing Nulls

In [21]:
df_train_clean.isnull().sum()

Time_spent_Alone             1190
Stage_fear                   1893
Social_event_attendance      1180
Going_outside                1466
Drained_after_socializing    1149
Friends_circle_size          1054
Post_frequency               1264
Personality                     0
dtype: int64

In [22]:
np.round(df_train_clean.isnull().sum() * 100 / df_train_clean.count(), 1)

Time_spent_Alone              6.9
Stage_fear                   11.4
Social_event_attendance       6.8
Going_outside                 8.6
Drained_after_socializing     6.6
Friends_circle_size           6.0
Post_frequency                7.3
Personality                   0.0
dtype: float64

In [23]:
np.round(df_test_clean.isnull().sum() * 100 / df_test_clean.count(), 1)

Time_spent_Alone              7.4
Stage_fear                   10.7
Social_event_attendance       6.9
Going_outside                 8.2
Drained_after_socializing     7.5
Friends_circle_size           6.0
Post_frequency                7.1
dtype: float64

Approx. same number of nulls in training and testing...

In [29]:
df_train_clean.mode()

Time_spent_Alone  Stage_fear  Social_event_attendance  Going_outside  \
0               0.0         0.0                      4.0            5.0   

   Drained_after_socializing  Friends_circle_size  Post_frequency  Personality  
0                        0.0                  5.0             3.0            1

In [ ]:
df_train_clean.fillna(df_train_clean.mode()).isna().sum()
# !FIXME 

Time_spent_Alone             1190
Stage_fear                   1893
Social_event_attendance      1180
Going_outside                1466
Drained_after_socializing    1149
Friends_circle_size          1054
Post_frequency               1264
Personality                     0
dtype: int64